### ISSUE TITLE
Build your own reactjs

### ISSUE THREAD

**Issue by itsprakash87** [danistefanovic/build-your-own-x#214]
### Main programming language
Javascript

### Tutorial title
Reimplementing react library

### Tutorial URL
https://github.com/itsprakash87/rereact

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [ ] Database
* [ ] Docker
* [ ] Emulator
* [x] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by phinishingit** [comment]
Y

On Jun 26, 2018 2:47 PM, "Prakash sharma" <notifications@github.com> wrote:

Main programming language

Javascript
Tutorial title

Reimplementing react library
Tutorial URL

https://github.com/itsprakash87/rereact
Category

   - 3D Renderer
   - Augmented Reality
   - BitTorrent Client
   - Blockchain / Cryptocurrency
   - Bot
   - Database
   - Docker
   - Emulator
   - Front-end Framework / Library
   - Game
   - Git
   - Network Stack
   - Neural Network
   - Operating System
   - Physics Engine
   - Programming Language
   - Regex Engine
   - Search Engine
   - Shell
   - Template Engine
   - Visual Recognition System
   - Web Search Engine
   - Web Server
   - Uncategorized

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danistefanovic/build-your-own-x/issues/214>, or mute
the thread

**Comment by zfrisch** [comment]
I think it's a fine topic for learning purposes. In fact, I'm interested in a tutorial, but unless I'm missing something this isn't a tutorial. it's just the finished result of your reimplementation, right?

**Comment by itsprakash87** [comment]
@zfrisch Yes, you are right. This isn't a tutorial. Anyway, I am in the process of creating a tutorial too. It would be better to reopen it once I am done with the tutorial. So closing it for now.

**Comment by danistefanovic** [comment]
@zfrisch Thanks for reviewing! 🙌
