### ISSUE TITLE
URL link not working, server moved or deleted.

### ISSUE THREAD

**Issue by IAmSeraph** [danistefanovic/build-your-own-x#453]
* Title: Java: 3D Game Development with LWJGL 3
* Programming Language: Java
* Category: Game
* URL: https://lwjglgamedev.gitbooks.io/3d-game-development-with-lwjgl/content/

The link doesn't work anymore, the server has either been moved or deleted.

**Comment by danistefanovic** [comment]
The link seems to work on my end:


![image](https://user-images.githubusercontent.com/1736595/78402909-ba3ca880-75fb-11ea-91f0-e9ed81869290.png)

**Comment by IAmSeraph** [comment]
![Screenshot_20200404-121816_Samsung Internet](https://user-images.githubusercontent.com/5700945/78424530-90709980-766e-11ea-81b4-abcfe012c632.jpg)
Screenshot from my phone, same result with firefox on my desktop.

**Comment by IAmSeraph** [comment]
I suppose it could be blocked in my country for whatever reason if it works on your end

**Comment by itoshkov** [comment]
I can also see the page. I can also experienced a similar problem with the site that we are developing. At first I couldn't access it. After awhile I could but it was very slow. After some digging around I tried accessing it through a proxy from a different country and it was working normally.

I think many of these problems are caused by the increased load on the internet because of the quarantine.
