### ISSUE TITLE
Add Nand2Tetris 

### ISSUE THREAD

**Issue by MustafaHaddara** [danistefanovic/build-your-own-x#60]
- **Main programming language (max. 1)**: any?
- **Tutorial title**: Nand2Tetris
- **Tutorial URL**: http://nand2tetris.org/course.php
- **Category**: Operating Systems, Compilers, Hardware

build your own computer starting from logic gates all the way to a GUI and tetris.

**Comment by danistefanovic** [comment]
Thanks!

**Comment by AndyPro720** [comment]
I was wondering why was this in the uncategorized section?

**Comment by bweston92** [comment]
It is 404ing

**Comment by parro-it** [comment]
https://www.nand2tetris.org/ works. BTW, I take the first of the course last year, it was really fun and interesting.

**Comment by AndyPro720** [comment]
Yeah I meant, a) we should segregate the two parts of the course and b) categorize them. They are too good to be in misc xD.

The first part could be in either of; How to build a computer, assembly and machine language.
Second part is, OOP language (like java), Virtual Machine, and a basic OS.

What say?

**Comment by nvas** [comment]
Each week in this course is a "standalone" project, so each one can be considered as a separate _build-your-own-x_ project.

**Comment by AndyPro720** [comment]
I agree.  Here's a mockup:

Week 1: Build your own logic gates.  Language HDL
Week 2: Build your own multi bit adder and ALU.  Language HDL
Week 3: Build your own memory chips(RAM, program counter).  Language HDL
Week 4: Build your own machine and assembly language. Language: Binary and Assembly
Week 5: Create your own computer architecture. Language: HDL, Logicism etc
Week 6: Program a assembler. Language: Any

Although a disclaimer that you need to understand the upper layers to create these, rather than pick up any one.

Also, this is only the first part of the course. xD
